export const whatsappChatTheme = {
  colors: {
    primary: '#E91E63',
    accent_green: '#FCE4EC',
    white: '#FFFFFF',
    grey_gainsboro: '#F3E5F5',
    grey: '#8696A0',
    black: '#111B21',
    dark_green: '#C2185B',
    light_green: '#E91E63',
  },
  messageList: {
    container: {
      backgroundColor: '#EFEAE2',
      flex: 1,
    },
  },
  messageSimple: {
    content: {
      container: {
        marginVertical: 1,
        marginHorizontal: 8,
      },
      containerInner: {
        backgroundColor: '#FCE4EC',
        borderRadius: 8,
        borderBottomRightRadius: 2,
        paddingHorizontal: 8,
        paddingVertical: 6,
        maxWidth: '85%',
        alignSelf: 'flex-end',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.12,
        shadowRadius: 1.0,
        elevation: 1,
      },
      containerInnerIncoming: {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        borderBottomLeftRadius: 2,
        paddingHorizontal: 8,
        paddingVertical: 6,
        maxWidth: '85%',
        alignSelf: 'flex-start',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.12,
        shadowRadius: 1.0,
        elevation: 1,
      },
      text: {
        fontSize: 14.5,
        color: '#111B21',
        lineHeight: 19,
      },
      metaContainer: {
        marginTop: 2,
        alignSelf: 'flex-end',
        flexDirection: 'row',
        alignItems: 'center',
      },
      metaText: {
        fontSize: 11,
        color: '#667781',
        marginRight: 4,
      },
    },
  },
  messageInput: {
    container: {
      backgroundColor: '#F0F2F5',
      paddingHorizontal: 8,
      paddingVertical: 6,
      flexDirection: 'row',
      alignItems: 'flex-end',
    },
    inputBoxContainer: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: 24,
      marginHorizontal: 4,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 40,
      maxHeight: 100,
      elevation: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
    },
    inputBox: {
      fontSize: 16,
      color: '#1F2937',
      textAlignVertical: 'center',
    },
    sendButton: {
      backgroundColor: '#E91E63',
      borderRadius: 24,
      width: 48,
      height: 48,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 4,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    attachButton: {
      padding: 8,
      justifyContent: 'center',
      alignItems: 'center',
    },
  },
};